spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ToshihiroArisawa/springapps-petclinic-microservices
        native:
          search-locations: classpath:.
  profiles:
    active: native
